-- ================================================================
-- CASA DO BRASIL LISBOA - SCRIPT COMPLETO MySQL
-- Execute TUDO de uma vez no phpMyAdmin
-- Servidor WePanel: https://lhwp3020.webapps.net:2443/
-- ================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ========== PARTE 1: CRIAR TABELAS ==========

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  telefone VARCHAR(30) NOT NULL DEFAULT '',
  tipo VARCHAR(20) DEFAULT 'funcionario',
  ativo TINYINT(1) DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS funcionarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(20) UNIQUE,
  nome_completo VARCHAR(200) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  telefone VARCHAR(30),
  cargo VARCHAR(100),
  nivel_acesso VARCHAR(20) DEFAULT 'funcionario',
  usuario_login VARCHAR(100),
  senha_hash VARCHAR(255) NOT NULL,
  ativo_login TINYINT(1) DEFAULT 1,
  ativo TINYINT(1) DEFAULT 1,
  reset_token VARCHAR(255),
  token_validade DATETIME,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS familias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_referencia VARCHAR(150),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pessoas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_completo VARCHAR(200) NOT NULL,
  data_nascimento DATE NOT NULL,
  naturalidade VARCHAR(100),
  nacionalidade VARCHAR(100) NOT NULL,
  genero VARCHAR(20),
  estado_civil VARCHAR(50),
  profissao VARCHAR(100),
  habilitacoes_literarias VARCHAR(120),
  idioma_origem VARCHAR(100),
  email VARCHAR(100),
  telefone VARCHAR(30),
  telefone_alternativo VARCHAR(30),
  morada TEXT,
  codigo_postal VARCHAR(20),
  distrito VARCHAR(100),
  concelho VARCHAR(100),
  freguesia VARCHAR(100),
  tipo_documento VARCHAR(50),
  numero_documento VARCHAR(50),
  documento_emissao DATE,
  documento_validade DATE,
  situacao_regular VARCHAR(50),
  tipo_visto VARCHAR(80),
  tipo_ar VARCHAR(80),
  status VARCHAR(20) DEFAULT 'ativo',
  observacoes TEXT,
  familia_id INT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  criado_por INT,
  FOREIGN KEY (familia_id) REFERENCES familias(id),
  FOREIGN KEY (criado_por) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS atendimentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  beneficiario_id INT NOT NULL,
  modalidade_atendimento VARCHAR(30),
  tipo_atendimento VARCHAR(100) NOT NULL,
  data_atendimento DATE NOT NULL,
  declaracao_data DATE,
  declaracao_local VARCHAR(150),
  declaracao_assinatura VARCHAR(150),
  descricao TEXT,
  observacoes TEXT,
  itens_entregues TEXT,
  funcionario_id INT NULL,
  elegivel_npt TINYINT(1),
  orientacao_profissional TINYINT(1),
  avaliou VARCHAR(20),
  servico_util VARCHAR(20),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (beneficiario_id) REFERENCES pessoas(id) ON DELETE CASCADE,
  FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS documentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pessoa_id INT,
  atendimento_id INT,
  tipo_documento VARCHAR(50) NOT NULL,
  nome_arquivo VARCHAR(255) NOT NULL,
  caminho_arquivo VARCHAR(500) NOT NULL,
  tamanho_bytes BIGINT,
  mimetype VARCHAR(100),
  criado_por INT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pessoa_id) REFERENCES pessoas(id) ON DELETE CASCADE,
  FOREIGN KEY (atendimento_id) REFERENCES atendimentos(id) ON DELETE SET NULL,
  FOREIGN KEY (criado_por) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS parentescos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pessoa_id INT NOT NULL,
  parente_id INT NOT NULL,
  grau_parentesco VARCHAR(50) NOT NULL,
  observacoes TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_parentesco (pessoa_id, parente_id),
  FOREIGN KEY (pessoa_id) REFERENCES pessoas(id) ON DELETE CASCADE,
  FOREIGN KEY (parente_id) REFERENCES pessoas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paises (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo_iso VARCHAR(3),
  nome VARCHAR(100),
  nome_pt VARCHAR(100),
  continente VARCHAR(50),
  ativo TINYINT(1) DEFAULT 1,
  UNIQUE KEY uk_codigo_iso (codigo_iso)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_atendimentos_data ON atendimentos(data_atendimento);
CREATE INDEX idx_atendimentos_beneficiario ON atendimentos(beneficiario_id);
CREATE INDEX idx_atendimentos_funcionario ON atendimentos(funcionario_id);
CREATE INDEX idx_pessoas_genero ON pessoas(genero);
CREATE INDEX idx_pessoas_data_nascimento ON pessoas(data_nascimento);
CREATE INDEX idx_pessoas_numero_documento ON pessoas(numero_documento);
CREATE INDEX idx_pessoas_familia ON pessoas(familia_id);
CREATE INDEX idx_parentescos_pessoa ON parentescos(pessoa_id);
CREATE INDEX idx_parentescos_parente ON parentescos(parente_id);
CREATE INDEX idx_documentos_pessoa ON documentos(pessoa_id);
CREATE INDEX idx_documentos_atendimento ON documentos(atendimento_id);

SET FOREIGN_KEY_CHECKS = 1;

-- ========== PARTE 2: INSERIR PAÍSES (249 países) ==========

INSERT IGNORE INTO paises (codigo_iso, nome, nome_pt, continente, ativo)
VALUES
  ('AF', 'Afghanistan', 'Afghanistan', 'Asia', 1),
  ('AX', 'Åland Islands', 'Åland Islands', 'Europe', 1),
  ('AL', 'Albania', 'Albania', 'Europe', 1),
  ('DZ', 'Algeria', 'Algeria', 'Africa', 1),
  ('AS', 'American Samoa', 'American Samoa', 'Oceania', 1),
  ('AD', 'Andorra', 'Andorra', 'Europe', 1),
  ('AO', 'Angola', 'Angola', 'Africa', 1),
  ('AI', 'Anguilla', 'Anguilla', 'Americas', 1),
  ('AQ', 'Antarctica', 'Antarctica', NULL, 1),
  ('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Americas', 1),
  ('AR', 'Argentina', 'Argentina', 'Americas', 1),
  ('AM', 'Armenia', 'Armenia', 'Asia', 1),
  ('AW', 'Aruba', 'Aruba', 'Americas', 1),
  ('AU', 'Australia', 'Australia', 'Oceania', 1),
  ('AT', 'Austria', 'Austria', 'Europe', 1),
  ('AZ', 'Azerbaijan', 'Azerbaijan', 'Asia', 1),
  ('BS', 'Bahamas', 'Bahamas', 'Americas', 1),
  ('BH', 'Bahrain', 'Bahrain', 'Asia', 1),
  ('BD', 'Bangladesh', 'Bangladesh', 'Asia', 1),
  ('BB', 'Barbados', 'Barbados', 'Americas', 1),
  ('BY', 'Belarus', 'Belarus', 'Europe', 1),
  ('BE', 'Belgium', 'Belgium', 'Europe', 1),
  ('BZ', 'Belize', 'Belize', 'Americas', 1),
  ('BJ', 'Benin', 'Benin', 'Africa', 1),
  ('BM', 'Bermuda', 'Bermuda', 'Americas', 1),
  ('BT', 'Bhutan', 'Bhutan', 'Asia', 1),
  ('BO', 'Bolivia, Plurinational State of', 'Bolivia, Plurinational State of', 'Americas', 1),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'Americas', 1),
  ('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Europe', 1),
  ('BW', 'Botswana', 'Botswana', 'Africa', 1),
  ('BV', 'Bouvet Island', 'Bouvet Island', 'Americas', 1),
  ('BR', 'Brazil', 'Brazil', 'Americas', 1),
  ('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'Africa', 1),
  ('BN', 'Brunei Darussalam', 'Brunei Darussalam', 'Asia', 1),
  ('BG', 'Bulgaria', 'Bulgaria', 'Europe', 1),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'Africa', 1),
  ('BI', 'Burundi', 'Burundi', 'Africa', 1),
  ('CV', 'Cabo Verde', 'Cabo Verde', 'Africa', 1),
  ('KH', 'Cambodia', 'Cambodia', 'Asia', 1),
  ('CM', 'Cameroon', 'Cameroon', 'Africa', 1),
  ('CA', 'Canada', 'Canada', 'Americas', 1),
  ('KY', 'Cayman Islands', 'Cayman Islands', 'Americas', 1),
  ('CF', 'Central African Republic', 'Central African Republic', 'Africa', 1),
  ('TD', 'Chad', 'Chad', 'Africa', 1),
  ('CL', 'Chile', 'Chile', 'Americas', 1),
  ('CN', 'China', 'China', 'Asia', 1),
  ('CX', 'Christmas Island', 'Christmas Island', 'Oceania', 1),
  ('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'Oceania', 1),
  ('CO', 'Colombia', 'Colombia', 'Americas', 1),
  ('KM', 'Comoros', 'Comoros', 'Africa', 1),
  ('CG', 'Congo', 'Congo', 'Africa', 1),
  ('CD', 'Congo, Democratic Republic of the', 'Congo, Democratic Republic of the', 'Africa', 1),
  ('CK', 'Cook Islands', 'Cook Islands', 'Oceania', 1),
  ('CR', 'Costa Rica', 'Costa Rica', 'Americas', 1),
  ('CI', 'Côte d''Ivoire', 'Côte d''Ivoire', 'Africa', 1),
  ('HR', 'Croatia', 'Croatia', 'Europe', 1),
  ('CU', 'Cuba', 'Cuba', 'Americas', 1),
  ('CW', 'Curaçao', 'Curaçao', 'Americas', 1),
  ('CY', 'Cyprus', 'Cyprus', 'Asia', 1),
  ('CZ', 'Czechia', 'Czechia', 'Europe', 1),
  ('DK', 'Denmark', 'Denmark', 'Europe', 1),
  ('DJ', 'Djibouti', 'Djibouti', 'Africa', 1),
  ('DM', 'Dominica', 'Dominica', 'Americas', 1),
  ('DO', 'Dominican Republic', 'Dominican Republic', 'Americas', 1),
  ('EC', 'Ecuador', 'Ecuador', 'Americas', 1),
  ('EG', 'Egypt', 'Egypt', 'Africa', 1),
  ('SV', 'El Salvador', 'El Salvador', 'Americas', 1),
  ('GQ', 'Equatorial Guinea', 'Equatorial Guinea', 'Africa', 1),
  ('ER', 'Eritrea', 'Eritrea', 'Africa', 1),
  ('EE', 'Estonia', 'Estonia', 'Europe', 1),
  ('SZ', 'Eswatini', 'Eswatini', 'Africa', 1),
  ('ET', 'Ethiopia', 'Ethiopia', 'Africa', 1),
  ('FK', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)', 'Americas', 1),
  ('FO', 'Faroe Islands', 'Faroe Islands', 'Europe', 1),
  ('FJ', 'Fiji', 'Fiji', 'Oceania', 1),
  ('FI', 'Finland', 'Finland', 'Europe', 1),
  ('FR', 'France', 'France', 'Europe', 1),
  ('GF', 'French Guiana', 'French Guiana', 'Americas', 1),
  ('PF', 'French Polynesia', 'French Polynesia', 'Oceania', 1),
  ('TF', 'French Southern Territories', 'French Southern Territories', 'Africa', 1),
  ('GA', 'Gabon', 'Gabon', 'Africa', 1),
  ('GM', 'Gambia', 'Gambia', 'Africa', 1),
  ('GE', 'Georgia', 'Georgia', 'Asia', 1),
  ('DE', 'Germany', 'Germany', 'Europe', 1),
  ('GH', 'Ghana', 'Ghana', 'Africa', 1),
  ('GI', 'Gibraltar', 'Gibraltar', 'Europe', 1),
  ('GR', 'Greece', 'Greece', 'Europe', 1),
  ('GL', 'Greenland', 'Greenland', 'Americas', 1),
  ('GD', 'Grenada', 'Grenada', 'Americas', 1),
  ('GP', 'Guadeloupe', 'Guadeloupe', 'Americas', 1),
  ('GU', 'Guam', 'Guam', 'Oceania', 1),
  ('GT', 'Guatemala', 'Guatemala', 'Americas', 1),
  ('GG', 'Guernsey', 'Guernsey', 'Europe', 1),
  ('GN', 'Guinea', 'Guinea', 'Africa', 1),
  ('GW', 'Guinea-Bissau', 'Guinea-Bissau', 'Africa', 1),
  ('GY', 'Guyana', 'Guyana', 'Americas', 1),
  ('HT', 'Haiti', 'Haiti', 'Americas', 1),
  ('HM', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Oceania', 1),
  ('VA', 'Holy See', 'Holy See', 'Europe', 1),
  ('HN', 'Honduras', 'Honduras', 'Americas', 1),
  ('HK', 'Hong Kong', 'Hong Kong', 'Asia', 1),
  ('HU', 'Hungary', 'Hungary', 'Europe', 1),
  ('IS', 'Iceland', 'Iceland', 'Europe', 1),
  ('IN', 'India', 'India', 'Asia', 1),
  ('ID', 'Indonesia', 'Indonesia', 'Asia', 1),
  ('IR', 'Iran, Islamic Republic of', 'Iran, Islamic Republic of', 'Asia', 1),
  ('IQ', 'Iraq', 'Iraq', 'Asia', 1),
  ('IE', 'Ireland', 'Ireland', 'Europe', 1),
  ('IM', 'Isle of Man', 'Isle of Man', 'Europe', 1),
  ('IL', 'Israel', 'Israel', 'Asia', 1),
  ('IT', 'Italy', 'Italy', 'Europe', 1),
  ('JM', 'Jamaica', 'Jamaica', 'Americas', 1),
  ('JP', 'Japan', 'Japan', 'Asia', 1),
  ('JE', 'Jersey', 'Jersey', 'Europe', 1),
  ('JO', 'Jordan', 'Jordan', 'Asia', 1),
  ('KZ', 'Kazakhstan', 'Kazakhstan', 'Asia', 1),
  ('KE', 'Kenya', 'Kenya', 'Africa', 1),
  ('KI', 'Kiribati', 'Kiribati', 'Oceania', 1),
  ('KP', 'Korea, Democratic People''s Republic of', 'Korea, Democratic People''s Republic of', 'Asia', 1),
  ('KR', 'Korea, Republic of', 'Korea, Republic of', 'Asia', 1),
  ('KW', 'Kuwait', 'Kuwait', 'Asia', 1),
  ('KG', 'Kyrgyzstan', 'Kyrgyzstan', 'Asia', 1),
  ('LA', 'Lao People''s Democratic Republic', 'Lao People''s Democratic Republic', 'Asia', 1),
  ('LV', 'Latvia', 'Latvia', 'Europe', 1),
  ('LB', 'Lebanon', 'Lebanon', 'Asia', 1),
  ('LS', 'Lesotho', 'Lesotho', 'Africa', 1),
  ('LR', 'Liberia', 'Liberia', 'Africa', 1),
  ('LY', 'Libya', 'Libya', 'Africa', 1),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'Europe', 1),
  ('LT', 'Lithuania', 'Lithuania', 'Europe', 1),
  ('LU', 'Luxembourg', 'Luxembourg', 'Europe', 1),
  ('MO', 'Macao', 'Macao', 'Asia', 1),
  ('MG', 'Madagascar', 'Madagascar', 'Africa', 1),
  ('MW', 'Malawi', 'Malawi', 'Africa', 1),
  ('MY', 'Malaysia', 'Malaysia', 'Asia', 1),
  ('MV', 'Maldives', 'Maldives', 'Asia', 1),
  ('ML', 'Mali', 'Mali', 'Africa', 1),
  ('MT', 'Malta', 'Malta', 'Europe', 1),
  ('MH', 'Marshall Islands', 'Marshall Islands', 'Oceania', 1),
  ('MQ', 'Martinique', 'Martinique', 'Americas', 1),
  ('MR', 'Mauritania', 'Mauritania', 'Africa', 1),
  ('MU', 'Mauritius', 'Mauritius', 'Africa', 1),
  ('YT', 'Mayotte', 'Mayotte', 'Africa', 1),
  ('MX', 'Mexico', 'Mexico', 'Americas', 1),
  ('FM', 'Micronesia, Federated States of', 'Micronesia, Federated States of', 'Oceania', 1),
  ('MD', 'Moldova, Republic of', 'Moldova, Republic of', 'Europe', 1),
  ('MC', 'Monaco', 'Monaco', 'Europe', 1),
  ('MN', 'Mongolia', 'Mongolia', 'Asia', 1),
  ('ME', 'Montenegro', 'Montenegro', 'Europe', 1),
  ('MS', 'Montserrat', 'Montserrat', 'Americas', 1),
  ('MA', 'Morocco', 'Morocco', 'Africa', 1),
  ('MZ', 'Mozambique', 'Mozambique', 'Africa', 1),
  ('MM', 'Myanmar', 'Myanmar', 'Asia', 1),
  ('NA', 'Namibia', 'Namibia', 'Africa', 1),
  ('NR', 'Nauru', 'Nauru', 'Oceania', 1),
  ('NP', 'Nepal', 'Nepal', 'Asia', 1),
  ('NL', 'Netherlands, Kingdom of the', 'Netherlands, Kingdom of the', 'Europe', 1),
  ('NC', 'New Caledonia', 'New Caledonia', 'Oceania', 1),
  ('NZ', 'New Zealand', 'New Zealand', 'Oceania', 1),
  ('NI', 'Nicaragua', 'Nicaragua', 'Americas', 1),
  ('NE', 'Niger', 'Niger', 'Africa', 1),
  ('NG', 'Nigeria', 'Nigeria', 'Africa', 1),
  ('NU', 'Niue', 'Niue', 'Oceania', 1),
  ('NF', 'Norfolk Island', 'Norfolk Island', 'Oceania', 1),
  ('MK', 'North Macedonia', 'North Macedonia', 'Europe', 1),
  ('MP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'Oceania', 1),
  ('NO', 'Norway', 'Norway', 'Europe', 1),
  ('OM', 'Oman', 'Oman', 'Asia', 1),
  ('PK', 'Pakistan', 'Pakistan', 'Asia', 1),
  ('PW', 'Palau', 'Palau', 'Oceania', 1),
  ('PS', 'Palestine, State of', 'Palestine, State of', 'Asia', 1),
  ('PA', 'Panama', 'Panama', 'Americas', 1),
  ('PG', 'Papua New Guinea', 'Papua New Guinea', 'Oceania', 1),
  ('PY', 'Paraguay', 'Paraguay', 'Americas', 1),
  ('PE', 'Peru', 'Peru', 'Americas', 1),
  ('PH', 'Philippines', 'Philippines', 'Asia', 1),
  ('PN', 'Pitcairn', 'Pitcairn', 'Oceania', 1),
  ('PL', 'Poland', 'Poland', 'Europe', 1),
  ('PT', 'Portugal', 'Portugal', 'Europe', 1),
  ('PR', 'Puerto Rico', 'Puerto Rico', 'Americas', 1),
  ('QA', 'Qatar', 'Qatar', 'Asia', 1),
  ('RE', 'Réunion', 'Réunion', 'Africa', 1),
  ('RO', 'Romania', 'Romania', 'Europe', 1),
  ('RU', 'Russian Federation', 'Russian Federation', 'Europe', 1),
  ('RW', 'Rwanda', 'Rwanda', 'Africa', 1),
  ('BL', 'Saint Barthélemy', 'Saint Barthélemy', 'Americas', 1),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 1),
  ('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'Americas', 1),
  ('LC', 'Saint Lucia', 'Saint Lucia', 'Americas', 1),
  ('MF', 'Saint Martin (French part)', 'Saint Martin (French part)', 'Americas', 1),
  ('PM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'Americas', 1),
  ('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Americas', 1),
  ('WS', 'Samoa', 'Samoa', 'Oceania', 1),
  ('SM', 'San Marino', 'San Marino', 'Europe', 1),
  ('ST', 'Sao Tome and Principe', 'Sao Tome and Principe', 'Africa', 1),
  ('SA', 'Saudi Arabia', 'Saudi Arabia', 'Asia', 1),
  ('SN', 'Senegal', 'Senegal', 'Africa', 1),
  ('RS', 'Serbia', 'Serbia', 'Europe', 1),
  ('SC', 'Seychelles', 'Seychelles', 'Africa', 1),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'Africa', 1),
  ('SG', 'Singapore', 'Singapore', 'Asia', 1),
  ('SX', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)', 'Americas', 1),
  ('SK', 'Slovakia', 'Slovakia', 'Europe', 1),
  ('SI', 'Slovenia', 'Slovenia', 'Europe', 1),
  ('SB', 'Solomon Islands', 'Solomon Islands', 'Oceania', 1),
  ('SO', 'Somalia', 'Somalia', 'Africa', 1),
  ('ZA', 'South Africa', 'South Africa', 'Africa', 1),
  ('GS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'Americas', 1),
  ('SS', 'South Sudan', 'South Sudan', 'Africa', 1),
  ('ES', 'Spain', 'Spain', 'Europe', 1),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'Asia', 1),
  ('SD', 'Sudan', 'Sudan', 'Africa', 1),
  ('SR', 'Suriname', 'Suriname', 'Americas', 1),
  ('SJ', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'Europe', 1),
  ('SE', 'Sweden', 'Sweden', 'Europe', 1),
  ('CH', 'Switzerland', 'Switzerland', 'Europe', 1),
  ('SY', 'Syrian Arab Republic', 'Syrian Arab Republic', 'Asia', 1),
  ('TW', 'Taiwan, Province of China', 'Taiwan, Province of China', NULL, 1),
  ('TJ', 'Tajikistan', 'Tajikistan', 'Asia', 1),
  ('TZ', 'Tanzania, United Republic of', 'Tanzania, United Republic of', 'Africa', 1),
  ('TH', 'Thailand', 'Thailand', 'Asia', 1),
  ('TL', 'Timor-Leste', 'Timor-Leste', 'Asia', 1),
  ('TG', 'Togo', 'Togo', 'Africa', 1),
  ('TK', 'Tokelau', 'Tokelau', 'Oceania', 1),
  ('TO', 'Tonga', 'Tonga', 'Oceania', 1),
  ('TT', 'Trinidad and Tobago', 'Trinidad and Tobago', 'Americas', 1),
  ('TN', 'Tunisia', 'Tunisia', 'Africa', 1),
  ('TR', 'Türkiye', 'Türkiye', 'Asia', 1),
  ('TM', 'Turkmenistan', 'Turkmenistan', 'Asia', 1),
  ('TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'Americas', 1),
  ('TV', 'Tuvalu', 'Tuvalu', 'Oceania', 1),
  ('UG', 'Uganda', 'Uganda', 'Africa', 1),
  ('UA', 'Ukraine', 'Ukraine', 'Europe', 1),
  ('AE', 'United Arab Emirates', 'United Arab Emirates', 'Asia', 1),
  ('GB', 'United Kingdom of Great Britain and Northern Ireland', 'United Kingdom of Great Britain and Northern Ireland', 'Europe', 1),
  ('US', 'United States of America', 'United States of America', 'Americas', 1),
  ('UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'Oceania', 1),
  ('UY', 'Uruguay', 'Uruguay', 'Americas', 1),
  ('UZ', 'Uzbekistan', 'Uzbekistan', 'Asia', 1),
  ('VU', 'Vanuatu', 'Vanuatu', 'Oceania', 1),
  ('VE', 'Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of', 'Americas', 1),
  ('VN', 'Viet Nam', 'Viet Nam', 'Asia', 1),
  ('VG', 'Virgin Islands (British)', 'Virgin Islands (British)', 'Americas', 1),
  ('VI', 'Virgin Islands (U.S.)', 'Virgin Islands (U.S.)', 'Americas', 1),
  ('WF', 'Wallis and Futuna', 'Wallis and Futuna', 'Oceania', 1),
  ('EH', 'Western Sahara', 'Western Sahara', 'Africa', 1),
  ('YE', 'Yemen', 'Yemen', 'Asia', 1),
  ('ZM', 'Zambia', 'Zambia', 'Africa', 1),
  ('ZW', 'Zimbabwe', 'Zimbabwe', 'Africa', 1);

-- ================================================================
-- FIM DO SCRIPT
-- Próximo passo: executar no PC: node scripts/setup-mysql.js
-- para inserir o admin (admin@casabrasil.pt / admin123)
-- ================================================================
